### ISSUE TITLE
how to crate the tectonic motion using the code directly

### ISSUE THREAD

**Issue by zhifengmuyun** [badlands-model/badlands#43]
Hello! I am very sorry to bother you again with a similar question. I learnt about the construction of the initial elevation of the surface and tectonic motion in the companion folder, but I didn't find out how to generate a tectonic file with 3D displacements as used in examples like rift or strike slip in the examples folder. Specifically, I would like to be able to use the code to specify the location of the fault in the study area, geometric elements such as the strike of the fault, and the slip rate. Can this be done using bandands?
Thank you for your help!

**Comment by GeoMattB** [comment]
Hi,
the displacement is specified as the distance that each point in the topography file moves and is limited to the resolution of your initial grid. You can't use a fault directly. Rate will be controlled by the start and end time in the tectonic scenarios. Z displacement is relatively simple as that is usually the end state you wish to attain. 
X and Y displacement I created by loading my XYZ topography points into QGIS, saving that as a geopackage and then adding the geometry attributes in QGIS to the gpkg (the original XYZ get saved as attributes). I then select the points within each fault block (using polygon selection) and move / drag those points by the slip amount and direction required. Then generate a new set of geometry attributes (the moved XYZ). Then its a simple originalX-movedX=dx etc to create the dx you need as an input for Badlands.
I ended up doing most of the input data creation in QGIS and saving the output to a gpkg file. Then used geo-pandas to create the badlands text file inputs.

My workflow was influenced by the tools I know how to use so there may be better ways to do this. If it's useful maybe I should make a youtubes or something.

**Comment by hakertop** [comment]
Hi GeoMattB

(Sorry, I don't know your true name)

I am interested in this topic as well because it seems that the badlands is a good platform to simulate strike-slip events . It is also hard for me to understand the meaning of the uplift0.csv from the example named strike-slip included the badlands example which want to express the displacement. I will appreciate that if you could upload a youtube video about how to make a csv file about the strike-slip displacement like uplift0.csv.

@zhifengmuyun could I get your email address? or you could get my email address (hakertop@163.com). I think we could discuss about this topic together.

Yangen

**Comment by GeoMattB** [comment]
Okay, I used QGIS when I did this.  I created a simple example of what I did here:
https://youtu.be/Qd6RgjhYY-g

**Comment by Marrah08039595303** [comment]
Hi everyone, This issue is part of my problem concerning how to go about the setting of the Badlands. I can only able to run the examples enclosed in the software, here I am looking a guide on how to about setting other parameters. therefore your contribution and guidance will be appreciated.Thank you

**Comment by tristan-salles** [comment]
Here is a link to badlands documentation, you might find it useful:
https://shorturl.at/zj1jr
